version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: examples/RateLimiter.Example/Dockerfile
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - ASPNETCORE_HTTPS_PORT=5001
